ARG BASE_CONTAINER=define_as_build_arg
FROM $BASE_CONTAINER
LABEL MAINTAINER="Jinyoung Park<jinyoung.park@colorado.edu>"

USER root
ENV DEBIAN_FRONTEND=noninteractive

# Remove jupyter kernel
RUN     echo "y" | /opt/conda/bin/jupyter-kernelspec remove -y \
        ir julia-1.10 # xcpp17 

# Install cpp-kernel
RUN pip install jupyter-cpp-kernel 

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
