ARG BASE_CONTAINER=define_as_build_arg
FROM ${BASE_CONTAINER}
LABEL MAINTAINER="CSEL Ops <cs-ops@colorado.edu>"

USER root

ENV DEBIAN_FRONTEND=noninteractive

#Dockerfile for CSCI3022 , DataScience Algorithm
# Install otter-grader and other packages required for 3022 class
RUN pip install \ 
      otter-grader pdfkit PyPDF2 plotly \
	jupysql \
	matplotlib \
	mdit-py-plugins \
	numpy \
	pandas \
	plotly \
	requests \
	scikit-image \
	scikit-learn \
	scipy \
	seaborn \
	statsmodels \
	sqlalchemy \
	ipywidgets \
	folium \
        numba \
        jupytext \
        widgetsnbextension \
        jupyterlab-widgets \
        simple-latex-checker

# Install R packages for otter-grader
#RUN R -e "devtools::install_github('ucbds-infra/ottr@stable')"

# Install misc
#RUN pip install  simple-latex-checker

RUN     rm -rf /home/jovyan  && \
        mkdir /home/jovyan && \
        chown $NB_UID:$NB_GID /home/jovyan

USER    $NB_UID
