name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to CSR Docker Registry
      uses: docker/login-action@v2
      with:
        registry: csr.csel.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Notebook Image
      run: docker pull csr.csel.io/jhub/notebook:v6.5.2.2

    - name: Build the Docker image
      run: make build-pl
